### PR TITLE
Approve button

### PR DESCRIPTION
**Pull request by Jasperkroes**
Whenever a boundingbox gets drawn a button shows up.
If this button is clicked then a text will get added to the "log".
This text shows the time since the game has started + "chest detected".
The button disappears whenever no bounding boxes are drawn or when it is clicked

### CODE REVIEW

**Comment by egedebruin** [comment]
wow such good

Only sometimes you need very fast reflexes om het te confirmen, dus een extra button maken voor unconfirm chest detected could help in this case, so the button will not be deleted every frame there isn't a chest.

**Comment by Jasperkroes** [comment]
ok shall we add it somewhere volgende week ofzo.

**Comment by egedebruin** [comment]
Yes that is a heel goed idee.

**Comment by lisv** [comment]
* I think the button should stay at its place for at least a minute, so that the host can take a calm look at it.
* It would be nice if the box that the question is about (box with the rectangle) would be visible next to the button, so that the host knows about what box/object the button is talking about.

While I do think that these changes are important, maybe we should focus on doing this next sprint.

**Comment by egedebruin** [comment]
@lisv I have changed now that it disappears when you click on it or unconfirm it. It isn't pretty, but it works I hope.

**Comment by Jasperkroes** [comment]
nadat een filmpje af is wordt de log geleegd. Ik weet niet zeker of dat is wat we willen.

Als je op chest detected drukt nadat het filmpje af is komt er een rare tijd te staan. Misschien moeten we die buttons weghalen als het filmpje af is ofzo.

**Comment by Jasperkroes** [comment]
oke de vorige opmerking is nu verholpen, echter doet reset application nu iets onverwachts; de application wordt niet gereset.

**Comment by Jasperkroes** [comment]
image

**Pull request merged**
